strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - static
  - docs

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pep8:
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 100

pylint:
  disable:
    - line-too-long
    - C0301
uses:
  - django
  - celery
